
stages:          # List of stages for jobs, and their order of execution
  - react-build
  - react-test
  - docker-build
  - docker-deploy

build:
  stage: react-build
  tags:
    - pwrsh
  image: node
  script: 
    - echo "Start building App"
    - npm install
    - npm run build
    - echo "Build successfully!"
  artifacts:
      expire_in: 1 hour
      paths:
        - build
        - node_modules/

test:
  stage: react-test
  tags:
    - pwrsh
  image: node
  script:
    - echo "Testing App"
    - npm test
    - echo "Test successfully!"
 

dockerbuild:

  stage: docker-build
  tags:
    - pwrsh
  image: docker:19.03
  services:
  - docker:19.03-dind

  before_script:
  - echo -n ${CI_REGISTRY_TOKEN} | docker login -u "${CI_REGISTRY_USER}" --password-stdin ${CI_REGISTRY}
  
  script:

    - 'echo ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}'

    - 'docker build --tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} .'

  only:

    - main



deploy:

  stage: docker-deploy
  tags:
    - pwrsh

  image: docker:19.03
  services:
  - docker:19.03-dind

  only:

    - main
  before_script:
  - echo -n ${CI_REGISTRY_TOKEN} | docker login -u "${CI_REGISTRY_USER}" --password-stdin ${CI_REGISTRY}
  script:

    - 'docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}'
