image: docker:19.03.12

services:
  - docker:19.03.12-dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci
  APP_NAME: springbootgitlab
  REPO: springbootlabtest
  DOCKER_TLS_CERTDIR: "/certs"

stages:
  - maven-build
  - docker-build
  - docker-push

maven-build:
  image: maven:3-jdk-11
  stage: maven-build
  script: "mvn clean package -Dmaven.test.skip=true -B"
  artifacts:
    paths:
      - target/*.jar



docker-build:
  stage: docker-build
  only:
    - main
  tags:
   - dockerpwrsh
  before_script:
  - echo -n ${CI_REGISTRY_TOKEN} | docker login -u "${CI_REGISTRY_USER}" --password-stdin ${CI_REGISTRY}
  script:
    - docker build --cache-from ${CI_REGISTRY_IMAGE}:latest --tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} .

# Tag the "master" branch as "latest"
Push latest:
  stage: docker-push
  tags:
   - dockerpwrsh
  only:
    - main
  before_script:
  - echo -n ${CI_REGISTRY_TOKEN} | docker login -u "${CI_REGISTRY_USER}" --password-stdin ${CI_REGISTRY}
  script:
    - 'docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}'

